/*
 * go_flutter_exam User
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

 package openapi

 import (
	 "net/http"
	 "github.com/mholt/binding"
	 "strconv"
 )
 
 // UserAddPost - Create a new User
 func UserAddPost(w http.ResponseWriter, r *http.Request) {
	 w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	 w.WriteHeader(http.StatusOK)
	 user := new (User)
	 userMap := GetUserMap()
	 binding.Bind(r, user)
	 user.Id = strconv.Itoa(len(userMap))
	 userMap[int64(len(userMap))] = user 
 }
 
 func (user *User) FieldMap(req *http.Request) binding.FieldMap {
	 return binding.FieldMap{
		 &user.Name: "name",
		 &user.Age:   "age",
	 }
 }
 